### ISSUE TITLE
Empty K_SINK propagated to underlying Knative Service when sink isn't ready

### ISSUE THREAD

**Issue by antoineco** [triggermesh/function#28]
I have a Function with the following sink configured:

```yaml
  sink:
    ref:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: SlackTarget
      name: chat-notifications
```

The sink is not ready yet:

```console
$ kubectl get slacktargets.targets.triggermesh.io
NAME                 URL   READY   REASON               AGE
chat-notifications         False   AdapterUnavailable   21m
```

However, the Function service is created immediately with an empty `K_SINK`, instead of waiting for the sink to become ready.

This causes unexpected behaviours because, instead of waiting for everything to be up, Triggers immediately fire events at the Function, which replies directly to the sender instead of shipping those events where they were supposed to be sent. As a result, the sender understands that everything went as expected, yet the final destination never received the payload.

It might be safer to report "NotReady" in the Function status if the sink's URL can't be determined, so that subscriptions pause the event flow.
